# Generated by Django 3.0.2 on 2020-01-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='dest',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
